export interface MemoryStoreData {
  projects: any[];
  skills: any[];
  blogs: any[];
  services: any[];
  experiences: any[];
  education: any[];
  certifications: any[];
  testimonials: any[];
  messages: any[];
  settings: any;
  now: any;
  aiKb: any[];
  auditLogs: any[];
}

export const memoryStore: MemoryStoreData = {
  projects: [
    {
      _id: 'proj-1',
      title: 'Nexus AI Workspaces',
      slug: 'nexus-ai-workspaces',
      description: 'Enterprise AI orchestration workspace with streaming collaborative canvases and LLM memory routers.',
      category: 'Full Stack',
      tags: ['Next.js 16', 'React 19', 'TypeScript', 'Node.js', 'MongoDB', 'Redis', 'Tailwind CSS'],
      metrics: '<120ms latency at 50k DAU',
      featured: true,
      order: 1,
      bentoSpan: 'col-span-2 row-span-2',
      problem: 'Teams struggle to collaborate with generative AI agents synchronously across stateful documents.',
      approach: 'Built an event-driven CRDT sync engine atop Node.js microservices and Redis state stores.',
      result: 'Achieved sub-120ms token distribution latency and eliminated multi-agent race conditions.',
      demoUrl: 'https://example.com/demo/nexus',
      githubUrl: 'https://github.com/example/nexus-ai-workspaces',
      image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
      keyFeatures: ['Multi-agent turn arbitration', 'Vector semantic memory cache', 'Sub-second collaborative CRDT canvas'],
    },
    {
      _id: 'proj-2',
      title: 'StreamFlow Distributed Pipeline',
      slug: 'streamflow-distributed-pipeline',
      description: 'High-throughput real-time telemetry processing backend handling millions of ingestion events.',
      category: 'Backend Architecture',
      tags: ['Node.js', 'TypeScript', 'Redis Streams', 'Docker', 'MongoDB Atlas'],
      metrics: '4.2M events/sec peak',
      featured: true,
      order: 2,
      bentoSpan: 'col-span-1 row-span-1',
      problem: 'Legacy ingestion systems throttled and dropped telemetry data during spike loads.',
      approach: 'Implemented distributed backpressure with Redis cluster queuing and partitioned worker workers.',
      result: 'Processed 4.2M events/sec without a single dropped packet over 99.995% SLA.',
      demoUrl: 'https://example.com/demo/streamflow',
      githubUrl: 'https://github.com/example/streamflow',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
      keyFeatures: ['Dynamic backpressure management', 'Zero-allocation buffer parser', 'Dead-letter automated replay'],
    },
    {
      _id: 'proj-3',
      title: 'Pulse Commerce Enterprise',
      slug: 'pulse-commerce-enterprise',
      description: 'Headless global retail commerce platform with sub-second catalog indexing and dynamic checkout.',
      category: 'Full Stack',
      tags: ['Next.js 16', 'TypeScript', 'MongoDB', 'Stripe', 'Tailwind CSS'],
      metrics: '99.99% checkout conversion',
      featured: true,
      order: 3,
      bentoSpan: 'col-span-1 row-span-1',
      problem: 'High cart abandonment due to multi-step legacy checkout workflows.',
      approach: 'Designed single-call optimistic checkout with Stripe Payment Element and edge caching.',
      result: 'Reduced checkout abandonment by 34% and improved mobile latency to 380ms.',
      demoUrl: 'https://example.com/demo/pulse',
      githubUrl: 'https://github.com/example/pulse-commerce',
      image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
      keyFeatures: ['Optimistic inventory reservation', 'Multi-currency settlement', 'Edge server-side rendered catalogs'],
    },
  ],
  skills: [
    { _id: 'sk-1', name: 'React 19', category: 'Frontend', level: 95, experience: '3+ Years', order: 1, icon: '', projects: ['nexus-ai-workspaces', 'pulse-commerce-enterprise'] },
    { _id: 'sk-2', name: 'Next.js 16', category: 'Frontend', level: 92, experience: '2+ Years', order: 2, icon: '', projects: ['nexus-ai-workspaces', 'pulse-commerce-enterprise'] },
    { _id: 'sk-3', name: 'TypeScript', category: 'Frontend', level: 90, experience: '3+ Years', order: 3, icon: '', projects: ['nexus-ai-workspaces', 'pulse-commerce-enterprise'] },
    { _id: 'sk-4', name: 'Node.js', category: 'Backend', level: 94, experience: '3+ Years', order: 4, icon: '', projects: ['streamflow-distributed-pipeline', 'nexus-ai-workspaces'] },
    { _id: 'sk-5', name: 'Express.js', category: 'Backend', level: 92, experience: '3+ Years', order: 5, icon: '', projects: ['streamflow-distributed-pipeline'] },
    { _id: 'sk-6', name: 'MongoDB Atlas', category: 'Database', level: 90, experience: '3+ Years', order: 6, icon: '', projects: ['pulse-commerce-enterprise', 'streamflow-distributed-pipeline'] },
    { _id: 'sk-7', name: 'PostgreSQL', category: 'Database', level: 85, experience: '2+ Years', order: 7, icon: '', projects: ['streamflow-distributed-pipeline'] },
    { _id: 'sk-8', name: 'Redis', category: 'Database', level: 88, experience: '2+ Years', order: 8, icon: '', projects: ['streamflow-distributed-pipeline'] },
    { _id: 'sk-9', name: 'Docker', category: 'DevOps & Cloud', level: 86, experience: '2+ Years', order: 9, icon: '', projects: ['streamflow-distributed-pipeline'] },
    { _id: 'sk-10', name: 'Tailwind CSS v4', category: 'Frontend', level: 95, experience: '3+ Years', order: 10, icon: '', projects: ['nexus-ai-workspaces'] },
  ],
  services: [
    {
      _id: 'srv-1',
      title: 'Full Stack Architecture & Web Apps',
      description: 'Turnkey development of mission-critical Next.js 16 and Node.js web applications designed for enterprise velocity and scale.',
      icon: 'Layers',
      features: ['Production Next.js 16 App', 'TypeScript REST & GraphQL APIs', 'Continuous Delivery pipeline'],
      deliverables: ['Production Next.js 16 App', 'TypeScript REST & GraphQL APIs', 'Continuous Delivery pipeline'],
      status: 'active',
      order: 1,
    },
    {
      _id: 'srv-2',
      title: 'Backend Systems & API Engineering',
      description: 'High-throughput Node.js microservices, distributed messaging, Redis caching layers, and resilient database schemas.',
      icon: 'Server',
      features: ['Sub-100ms response microservices', 'Database indexing & sharding design', 'End-to-end OpenAPI documentation'],
      deliverables: ['Sub-100ms response microservices', 'Database indexing & sharding design', 'End-to-end OpenAPI documentation'],
      status: 'active',
      order: 2,
    },
    {
      _id: 'srv-3',
      title: 'Performance & Architecture Auditing',
      description: 'Deep-dive analysis of bottlenecks across database queries, memory leaks, latency spikes, and Core Web Vitals.',
      icon: 'Cpu',
      features: ['Full architecture assessment', 'Actionable remediation roadmap', 'Hands-on performance refactoring'],
      deliverables: ['Full architecture assessment', 'Actionable remediation roadmap', 'Hands-on performance refactoring'],
      status: 'active',
      order: 3,
    },
  ],
  experiences: [
    {
      _id: 'exp-1',
      company: 'CloudScale Technologies',
      role: 'Senior Full Stack & Backend Engineer',
      duration: '2023 - Present',
      period: '2023 - Present',
      location: 'Remote, US',
      description: 'Architecting distributed Node.js microservices and Next.js frontend applications for 100k+ global active users.',
      technologies: ['Node.js', 'Next.js', 'TypeScript', 'MongoDB', 'Docker', 'Redis'],
      skills: ['Node.js', 'Next.js', 'TypeScript', 'MongoDB', 'Docker', 'Redis'],
      order: 1,
    },
    {
      _id: 'exp-2',
      company: 'HyperStack Labs',
      role: 'Full Stack Developer',
      duration: '2021 - 2023',
      period: '2021 - 2023',
      location: 'Bangalore, India',
      description: 'Built high-converting e-commerce web applications and real-time dashboard analytics utilizing MERN stack.',
      technologies: ['React', 'Express.js', 'MongoDB', 'Tailwind CSS', 'Redux'],
      skills: ['React', 'Express.js', 'MongoDB', 'Tailwind CSS', 'Redux'],
      order: 2,
    },
  ],
  education: [
    {
      _id: 'edu-1',
      degree: 'Bachelor of Science in Computer Science & Engineering',
      school: 'Institute of Engineering & Technology',
      period: '2019 - 2023',
      gpa: '3.8 / 4.0',
      highlights: ['Algorithms & Data Structures', 'Distributed Systems', 'Software Architecture'],
      order: 1,
    },
  ],
  certifications: [
    {
      _id: 'cert-1',
      title: 'AWS Certified Solutions Architect – Associate',
      provider: 'Amazon Web Services',
      issueDate: '2024',
      credentialID: 'AWS-SAA-839210',
      image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80',
      verifyURL: 'https://aws.amazon.com/verification',
      order: 1,
    },
    {
      _id: 'cert-2',
      title: 'MongoDB Certified Developer Associate',
      provider: 'MongoDB University',
      issueDate: '2023',
      credentialID: 'MDB-DEV-49201',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80',
      verifyURL: 'https://learn.mongodb.com/certificates',
      order: 2,
    },
  ],
  testimonials: [
    {
      _id: 'test-1',
      name: 'David Sterling',
      role: 'VP of Engineering',
      company: 'ApexScale Global',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      content: 'Basi rebuilt our core transaction pipeline from the ground up. His mastery of Node.js distributed patterns and clean Next.js architecture reduced our p99 latency by 85%.',
      rating: 5,
      order: 1,
    },
    {
      _id: 'test-2',
      name: 'Elena Rostova',
      role: 'Lead Product Manager',
      company: 'Vanguard Systems',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
      content: 'Working with Basi is a breath of fresh air. He does not just write code; he proactively audits edge cases, designs bulletproof APIs, and builds visually breathtaking frontends.',
      rating: 5,
      order: 2,
    },
  ],
  blogs: [
    {
      _id: 'blog-1',
      title: 'Architecting Resilient Real-Time Microservices with Node.js and Redis',
      slug: 'architecting-resilient-realtime-microservices',
      excerpt: 'A deep dive into distributed backpressure, atomic pub/sub leases, and fault-tolerant ingestion pipelines at scale.',
      category: 'Architecture',
      tags: ['Node.js', 'Distributed Systems', 'Redis', 'Backend'],
      readingTime: '7 min read',
      published: true,
      views: 1240,
      createdAt: new Date().toISOString(),
      coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
      content: 'Designing distributed backends requires rigorous guarantees around idempotency and message acknowledgment...',
    },
    {
      _id: 'blog-2',
      title: 'React 19 Server Actions and Next.js App Router in Enterprise Practice',
      slug: 'react-19-server-actions-enterprise-practice',
      excerpt: 'Benchmarking optimistic state mutations, form validation paradigms, and caching lifecycles in mission-critical applications.',
      category: 'Frontend Engineering',
      tags: ['React 19', 'Next.js', 'Performance', 'TypeScript'],
      readingTime: '5 min read',
      published: true,
      views: 980,
      createdAt: new Date().toISOString(),
      coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
      content: 'Server Actions decouple network orchestration from imperative client handlers while preserving zero-JS fallbacks...',
    },
  ],
  messages: [
    {
      _id: 'msg-1',
      name: 'Sarah Jenkins',
      email: 's.jenkins@vanguardtech.io',
      subject: 'Senior Backend Architect Opportunity',
      projectType: 'Recruitment',
      message: 'Hi Basi, your distributed pipeline project is extremely impressive. We are building a high-volume fintech transaction layer and would love to discuss a lead architect role.',
      read: false,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'msg-2',
      name: 'Marcus Vance',
      email: 'marcus@hypergrowth.co',
      subject: 'Consulting Inquiry: Real-time Microservices Audit',
      projectType: 'Consulting',
      message: 'Looking for a 2-week engagement to audit our Node.js and Redis messaging bottlenecks before our enterprise launch.',
      read: true,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  settings: {
    heroTitle: 'Crafting High-Performance Full Stack Systems',
    heroSubtitle: 'Senior MERN & Next.js Engineer specializing in scalable distributed backends and premium web apps.',
    email: 'basi.dev@example.com',
    phone: '+1 (555) 019-2834',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    resumeURL: '/resume.pdf',
    resumeUrl: '/resume.pdf',
    footerDescription: 'Designed with precision. Engineered for resilience.',
    footerContent: 'Designed with precision. Engineered for resilience.',
    socialLinks: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
      twitter: 'https://x.com',
      discord: '',
      leetcode: '',
    },
    stats: {
      totalVisitors: 1420,
      pageViews: 4890,
      projectViews: 1820,
      resumeDownloads: 342,
      contactSubmissions: 28,
    },
  },
  now: {
    lastUpdated: 'September 2026',
    currentFocus: 'High-throughput event streaming architectures and React 19 concurrent state systems.',
    building: ['Nexus AI Workspaces v2.0', 'Distributed CRDT document synchronizer'],
    learning: ['Rust systems programming for high-concurrency micro-daemons', 'eBPF network packet tracing'],
    reading: ['Designing Data-Intensive Applications (Kleppmann)', 'Database Internals (Petrov)'],
    seeking: 'Open to select high-impact Senior Full Stack / Backend engineering positions.',
  },
  aiKb: [
    { _id: 'kb-1', topic: 'Core Tech Stack', category: 'Technical', content: 'Specializes in MERN stack, Next.js 16, React 19, TypeScript, Docker, Redis, and high-performance microservices.' },
    { _id: 'kb-2', topic: 'Availability', category: 'Career', content: 'Currently open to senior full stack roles, contract consulting, and enterprise system architecture projects.' },
    { _id: 'kb-3', topic: 'Contact', category: 'General', content: 'Can be reached directly at basi.dev@example.com or through the website contact form.' },
  ],
  auditLogs: [
    {
      _id: 'aud-1',
      action: 'DEPLOYED',
      target: 'Production Release v2.4.0',
      author: 'Automated Pipeline',
      timestamp: '2026-09-25 09:30:14',
    },
    {
      _id: 'aud-2',
      action: 'SYNCED',
      target: 'AI Grounding Vector Knowledge Base',
      author: 'Claude Haiku Subsystem',
      timestamp: '2026-09-25 08:45:00',
    },
  ],
};
